//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartments()
        {
            this.Supplies = new HashSet<Supplies>();
        }
    
        public int ID { get; set; }
        public string Adress_City { get; set; }
        public string Adress_Street { get; set; }
        public string Adress_House { get; set; }
        public Nullable<int> Adress_Number { get; set; }
        public Nullable<int> FK_ID_Districts { get; set; }
        public Nullable<double> TotalArea { get; set; }
        public Nullable<int> Rooms { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> FK_Type_Object_ID { get; set; }
    
        public virtual Districts Districts { get; set; }
        public virtual Type_Object Type_Object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplies> Supplies { get; set; }
    }
}
