//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        public int ID { get; set; }
        public Nullable<int> Demant_ID { get; set; }
        public Nullable<int> Supply_ID { get; set; }
    
        public virtual Demands Demands { get; set; }
        public virtual Supplies Supplies { get; set; }
    }
}
