//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealEstateDBEntities : DbContext
    {
        public RealEstateDBEntities()
            : base("name=RealEstateDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<Apartments> Apartments { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Demands> Demands { get; set; }
        public virtual DbSet<Districts> Districts { get; set; }
        public virtual DbSet<Supplies> Supplies { get; set; }
        public virtual DbSet<Type_Object> Type_Object { get; set; }
    }
}
